

/***********CPL Communication********/

#define CMD_PV_VOLTAGE 1
#define CMD_PV_CURRENT 2
#define CMD_BATTERY_VOLTAGE 3
#define CMD_BATTERY_CURRENT 4
#define CMD_LED_CURRENT 5
#define CMD_LED_VOLTAGE 6
#define CMD_STATE_GIVE 7
#define CMD_STATE_DAY_NIGHT 8
#define CMD_EMERGENCY 9

#define REQUEST 1
#define RESPONSE 0

#define ID_MCU  1
#define ID_MCU2 2

#define FRAME_DATA_LENGTH   8


/******Supervision communication*******/

#define ADDR_SUPERVISION_JOUR_NUIT	0// Si == false mode jour ; Si == True mode nuit 
#define ADDR_SUPERVISION_V_BATTERY	100 // Float
#define ADDR_SUPERVISION_I_BATTERY	110 // Float
#define ADDR_SUPERVISION_P_BATTERY	120 // Float
#define ADDR_SUPERVISION_V_PV	130 // Float
#define ADDR_SUPERVISION_I_PV	140 // Float
#define ADDR_SUPERVISION_P_PV	150 // Float
#define ADDR_SUPERVISION_DC_PV	160 // uint16
#define ADDR_SUPERVISION_V_LED	170 // Float
#define ADDR_SUPERVISION_I_LED	180 // Float
#define ADDR_SUPERVISION_P_LED	190 // Float
#define ADDR_SUPERVISION_DC_LED	40 // uint16
#define ADDR_SUPERVISION_TEMPERATURE	43	// Float


#define ALARME_BATTERY_CHARGING	50
#define ALARME_BATTERY_FULL 	51
#define ALARME_BATTERY_LOW_VOLTAGE	52
#define ALARME_RELAY_CLOSE	53
#define ALARME_RELAY_OPEN	54
#define ALARME_CHARGING_OTHER_GRID	55
#define ALARME_DAY_FUNCTIONNEMENT	56
#define ALARME_NIGHT_FUNCTIONNEMENT	57
#define ALARME_LED_DRIVING	58
#define ALARME_LED_DIMMING	59
#define ALARM_ERROR_CRITICAL_SYSTEM	60
#define ALARME_BATTERY_NOT_FULL_NIGHT	61



#define TYPE_FLOAT_32b	4
#define TYPE_WORD_16b	1

#define ENTETE_SUPERVISION	0x1B
#define WRITE_SUPERVISION	0x57
